import { MenuItem } from './menudata.types';

const menuData: MenuItem[]= [
    {
      id: 1,
      title: "Medicina Estética",
      path: "/estetica",
      image:"/images/estetica.menu.jpg",
      newTab: false,
      submenu: [
        { 
          name: 'Tratamientos Faciales', 
          imageUrl: '/images/estetica.facial.jpeg',
          path: '/estetica/facial',
          services: [
            { serviceName: 'Rinomodelación Sin Cirugía', servicePath: '/estetica/facial/rinomodelacion'},
            { serviceName: 'Aumento De Labios', servicePath: '/estetica/facial/aumento-labios'},
            { serviceName: 'Dermapen', servicePath: '/estetica/facial/dermapen'},
            { serviceName: 'Dermopigmentación', servicePath: '/estetica/facial/dermopigmentacion'},
            { serviceName: 'Eliminar Arrugas', servicePath: '/estetica/facial/elimina-arrugas'},
            { serviceName: 'Enzimas Recombinantes Bioactivas', servicePath: '/estetica/facial/enzimas-bioactivas'},
            { serviceName: 'HIFU', servicePath: '/estetica/facial/hifu'},
            { serviceName: 'Hilos Tensores Foxy Eyes', servicePath: '/estetica/facial/foxy-eyes'},
            { serviceName: 'Hilos Tensores', servicePath: '/estetica/facial/hilos-tensores'},
            { serviceName: 'Láser CO2 Fraccionado', servicePath: '/estetica/facial/laser-co2'},
            { serviceName: 'Láser Q-Switch Neodimio', servicePath: '/estetica/facial/laser-qswitch'},
            { serviceName: 'Mesoterapia Facial', servicePath: '/estetica/facial/mesoterapia-facial'},
            { serviceName: 'Ozonoterapia', servicePath: '/estetica/facial/ozonoterapia-facial'},
            { serviceName: 'Peeling Químico', servicePath: '/estetica/facial/peeling'},
            { serviceName: 'Plasma Rico en Plaquetas PRP', servicePath: '/estetica/facial/plasma-prp'},
            { serviceName: 'Rejuvenecimiento con IPL', servicePath: '/estetica/facial/ipl'},
            { serviceName: 'Relleno de Ojeras', servicePath: '/estetica/facial/relleno-ojeras'},
            { serviceName: 'Relleno de Fillers', servicePath: '/estetica/facial/relleno-fillers'},
          ]
        },
        { 
          name: 'Tratamientos Corporales', 
          imageUrl: '/images/estetica.corporal.jpeg',
          path: '/estetica/corporal',
          services: [
            { serviceName: 'HIFU Corporal', servicePath: '/estetica/corporal/hifu-corporal'},
            { serviceName: 'Electroestimulación EMS', servicePath: '/estetica/corporal/ems'},
            { serviceName: 'Eliminación de la Sudoración Excessive', servicePath: '/estetica/corporal/elimina-sudor'},
            { serviceName: 'Eliminación de tatuajes', servicePath: '/estetica/corporal/elimina-tatuajes'},
            { serviceName: 'Enzimas Recombinantes Bioactivas', servicePath: '/estetica/corporal/enzimas-bioactivas'},
            { serviceName: 'Escleroterapia', servicePath: '/estetica/corporal/escleroterapia'},
            { serviceName: 'Mesoterapia Lipolítica', servicePath: '/estetica/corporal/mesoterapia-lipolitica'},
            { serviceName: 'Ozonoterapia Corporal', servicePath: '/estetica/corporal/ozonoterapia-corporal'},
            { serviceName: 'Presoterapia', servicePath: '/estetica/corporal/presoterapia'},
            { serviceName: 'T-Away Facial', servicePath: '/estetica/corporal/t-away'},
            { serviceName: 'VelaShape Remodelación Corporal', servicePath: '/estetica/corporal/mesoterapia'},
          ]
        },
        { 
          name: 'Medicina Estética Masculina', 
          imageUrl: '/images/estetica.masculina.jpg',
          path: '/estetica/masculina',
          services: [
            { serviceName: 'Corrección de la Nariz', servicePath: '/estetica/masculina/correccion-nariz'},
            { serviceName: 'Definición Mandibular', servicePath: '/estetica/masculina/definicion-mandibula'},
            { serviceName: 'Eliminar Bolsas', servicePath: '/estetica/masculina/elimina-bolsas'},
            { serviceName: 'Eliminar Papada sin Cirugía', servicePath: '/estetica/masculina/elimina-papada'},
            { serviceName: 'Parpados Caidos', servicePath: '/estetica/masculina/parpados'},
            { serviceName: 'Reducir Volumen Corporal', servicePath: '/estetica/masculina/reducir-volumen'},
            { serviceName: 'Rejuvenecimiento Facial', servicePath: '/estetica/masculina/rejuvenecimiento facial'},
            { serviceName: 'Trastornos de la Piel', servicePath: '/estetica/masculina/trastornos-piel'},
            { serviceName: 'Aumento de Pómulos', servicePath: '/estetica/masculina/aumento-pomulos'},
            { serviceName: 'Eliminar Ojeras', servicePath: '/estetica/masculina/elimina-ojeras'},
            { serviceName: 'Eliminar Sudoración Excesiva', servicePath: '/estetica/masculina/elimina-sudor'},
            { serviceName: 'Ginecomastia', servicePath: '/estetica/masculina/ginecomastia'},
            { serviceName: 'Marcación Abdominal', servicePath: '/estetica/masculina/marcacion-abdominal'},
            { serviceName: 'Otoplastia', servicePath: '/estetica/masculina/otoplastia'},
          ]
        },
        { 
          name: 'Cirugías', 
          imageUrl: '/images/estetica.cirugias.jpeg',
          path: '/estetica/cirugias',
          services: [
            { serviceName: 'Aumento de pecho', servicePath: '/estetica/cirugias/aumento-pecho'},
            { serviceName: 'Cambio de prótesis', servicePath: '/estetica/cirugias/cambio-protesis'},
            { serviceName: 'Elevación de pecho', servicePath: '/estetica/cirugias/elevacion-pecho'},
            { serviceName: 'Ginecomastia', servicePath: '/estetica/cirugias/ginecomastia'},
            { serviceName: 'Pezones Invertidos', servicePath: '/estetica/cirugias/pezones-invertidos'},
            { serviceName: 'Reconstrucción Mamaria', servicePath: '/estetica/cirugias/recontruccion-mamaria'},
            { serviceName: 'Reducción de Pecho', servicePath: '/estetica/cirugias/reduccion-pecho'},
            { serviceName: 'Abdominoplastia', servicePath: '/estetica/cirugias/abdominoplastia'},
            { serviceName: 'Aumento de Gluteos', servicePath: '/estetica/cirugias/aumento-gluteos'},
            { serviceName: 'Lifting de Brazos', servicePath: '/estetica/cirugias/lifting-brazos'},
            { serviceName: 'Lifting de Piernas', servicePath: '/estetica/cirugias/lifting-piernas'},
            { serviceName: 'Lipofilling', servicePath: '/estetica/cirugias/lipofilling'},
            { serviceName: 'Lipolaser', servicePath: '/estetica/cirugias/lipolaser'},
            { serviceName: 'Liposucción', servicePath: '/estetica/cirugias/liposuccion'},
            { serviceName: 'Rinoplastia', servicePath: '/estetica/cirugias/rinoplastia'},
            { serviceName: 'Bichetomia', servicePath: '/estetica/cirugias/bichetomia'},
            { serviceName: 'Blefaroplastia', servicePath: '/estetica/cirugias/blefaroplastia'},
            { serviceName: 'Lifting de Riesgo', servicePath: '/estetica/cirugias/lifting-riesgo'},
            { serviceName: 'Lifting Facial', servicePath: '/estetica/cirugias/lifting-facial'},
            { serviceName: 'Liposucción de Papada', servicePath: '/estetica/cirugias/liposuccion-papada'},
            { serviceName: 'Lobuloplastia', servicePath: '/estetica/cirugias/lobuloplastia'},
            { serviceName: 'Mentoplastia', servicePath: '/estetica/cirugias/mentoplastia'},
            { serviceName: 'Otoplastia', servicePath: '/estetica/cirugias/otoplastia'},
          ]
        },
        { name: ' Tratamientos Laser', path: '/estetica/laser', imageUrl: '/images/estetica.laser.jpeg' },
        ],
    },
    {
      id: 2,
      title: "Medicina Anti-Aging",
      path: "/anti-aging",
      image:"/images/antiaging.png",
      newTab: false,
      submenu: [
        { name: 'Equilibrio Hormonal Chip de la Juventud', imageUrl: '/images/estet.jpg', path: '/anti-aging/chip-juventud'},
        { name: 'Turismo de salud', imageUrl: '/images/medic.jpg', path: '/turismo-salud'},
        { name: 'Medicina Funcional y Nutrición Celular Ortomolecular', imageUrl: '/images/placeholder-image.png', path: '/anti-aging/nutricion-funcional'},
        { name: 'Sueroterapia', imageUrl: '/images/estetica.menu.jpg', path: '/anti-aging/sueroterapia'},
        { name: 'Ozonoterapia Médica y Estética', 
          imageUrl: '/images/anti-aging.ozonoterapia.png',
          path: '/anti-aging/ozonoterapia',
          services: [
            { serviceName: 'Ozonoterapia Capilar', servicePath: '/ozonoterapia-capilar'},
            { serviceName: 'Acné', servicePath: '/acne'},
            { serviceName: 'Celulitis', servicePath: '/celulitis'},
            { serviceName: 'Embellecimiento de la Piel', servicePath: '/embellecimiento-piel'},
            { serviceName: 'Post Cirugía', servicePath: '/post-cirugia'},
            { serviceName: 'Post Dermopigmentación', servicePath: '/post-dermopigmentacion'},
            { serviceName: 'Rejuvenecimiento Facial', servicePath: '/rejuvenecimiento facial'},
            { serviceName: 'Rosácea', servicePath: '/rosacea'},
            { serviceName: 'Varices y Arañas Vasculares', servicePath: '/varices'},
            { serviceName: 'Cadera', servicePath: '/ozonoterapia-cadera'},
            { serviceName: 'Codo', servicePath: '/ozonoterapia-codo'},
            { serviceName: 'Columna Vertebral', servicePath: '/ozonoterapia-columna'},
            { serviceName: 'Hombro', servicePath: '/ozonoterapia-hombro'},
            { serviceName: 'Mano', servicePath: '/ozonoterapia-mano'},
            { serviceName: 'Pie', servicePath: '/ozonoterapia-pie'},
            { serviceName: 'Rodilla', servicePath: '/ozonoterapia-rodilla'},
            { serviceName: 'Tobillo', servicePath: '/ozonoterapia-tobillo'},
            { serviceName: 'infecciones Ginecológicas', servicePath: '/infeccion-ginecologica'},
          ]
        },
        ],
    },
    {
      id: 3,
      title: "Alquiler y venta de equipos",
      path: "/equipos",
      image:"/images/equipos.menu.png",
      newTab: false,
      submenu: [
        { name: 'Equipos médicos', imageUrl: '/images/placeholder-image.png', path: '/medicos'},
        { name: 'Equipos estéticos', imageUrl: '/images/placeholder-image.png', path: '/esteticos'},
        { name: 'Equipos de dermopigmentación', imageUrl: '/images/placeholder-image.png', path: '/dermopigmentacion'},
        { name: 'Dispositivos para el cuidado de salud', imageUrl: '/images/placeholder-image.png', path: '/salud'},
        ],
    },
    {
      id: 4,
      title: "Formaciones",
      path: "/formación",
      image:"/images/formación.png",
      newTab: false,
      submenu: [
        { name: 'Dermopigmentación', imageUrl: '/images/formacion.dermopigmentacion.png', path: '/dermopigmentacion'},
        { name: 'Medicina Estética', imageUrl: '/images/formacion.medicinaestetica.png', path: '/medicina-estetica'},
        { name: 'Aparatología', imageUrl: '/images/formacion.aparatologia.png', path: '/aparatologia'},
        ],
    },
    {
      id: 5,
      title: "Tienda",
      path: "/tienda",
      image:"/images/tienda.menu.png",
      newTab: false,
      submenu: [
        { name: 'Material de Prácticas', imageUrl: '/images/tienda.practicas.png', path: '/material-practicas'},
        { name: 'Cosmética', imageUrl: '/images/tienda.cosmetica.png', path: '/cosmetica'},
        { name: 'Suplementos', imageUrl: '/images/tienda.suplementos.png', path: '/suplementos'},
        { name: 'Salud y belleza', imageUrl: '/images/tienda.salud.png', path: '/salud-y-belleza'},
        { name: 'Aparatología profesional', imageUrl: '/images/tienda.aparatologia.png', path: '/aparatologia'},
        ],
    },
    {
      id: 6,
      title: "Packs",
      path: "/packs",
      image:"/images/packs.menu.png",
      newTab: false,
      submenu: [
        { name: 'Packs Medicina Estetica', imageUrl: '/images/packs.estetica.png', path: '/medicina-estetica'},
        { name: 'Packs Medicina Anti-Aging', imageUrl: '/images/packs.anti-aging.png', path: '/medicina-anti-aging'},
        { name: 'Packs Equipos', imageUrl: '/images/packs.equipos.png', path: '/equipos'},
        { name: 'Packs Formación', imageUrl: '/images/packs.formaciones.png', path: '/formaciones'},

        ],
    },
  
  ];
  export default menuData;